import { useEffect, useMemo, useState } from 'react';
import CenterModal from '../components/CenterModal.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import ToastMessage from '../components/ToastMessage.jsx';
import { createCustomer, getCustomers, updateCustomer, updateCustomerAuthorization, updateCustomerCredit, updateCustomerStatus } from '../services/customerService.js';
import styles from '../styles/App.module.css';

const emptyCustomer = { name: '', email: '', password: '', businessName: '', commercialName: '', rfc: '', contactName: '', phone: '', address: '', city: '', state: '', postalCode: '', sanitaryLicense: '', isAuthorized: false, isActive: true, creditEnabled: false, creditLimit: 0, creditUsed: 0 };
function formValues(customer) { return customer ? { ...emptyCustomer, ...customer, password: '' } : emptyCustomer; }

export default function AdminCustomersPage() {
  const [customers, setCustomers] = useState([]); const [query, setQuery] = useState(''); const [metric, setMetric] = useState('');
  const [modal, setModal] = useState(null); const [form, setForm] = useState(emptyCustomer); const [error, setError] = useState(''); const [toast, setToast] = useState('');
  const load = async () => { try { setCustomers(await getCustomers()); setError(''); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []); useEffect(() => { if (!toast) return undefined; const id = setTimeout(() => setToast(''), 3200); return () => clearTimeout(id); }, [toast]);
  const metrics = useMemo(() => ({ active: customers.filter((item) => item.isActive).length, pending: customers.filter((item) => !item.isAuthorized).length, noLicense: customers.filter((item) => !item.sanitaryLicense).length, credit: customers.filter((item) => item.creditEnabled).length }), [customers]);
  const visible = useMemo(() => customers.filter((item) => {
    const searchable = [item.businessName, item.commercialName, item.rfc, item.email, item.contactName, item.city, item.state].join(' ').toLowerCase().includes(query.toLowerCase());
    const matchesMetric = !metric || (metric === 'active' && item.isActive) || (metric === 'pending' && !item.isAuthorized) || (metric === 'noLicense' && !item.sanitaryLicense) || (metric === 'credit' && item.creditEnabled);
    return searchable && matchesMetric;
  }), [customers, metric, query]);
  const toggle = (value) => setMetric((current) => current === value ? '' : value);
  const save = async (event) => { event.preventDefault(); try { let saved = modal?.id ? await updateCustomer(modal.id, form) : await createCustomer(form); if (modal?.id) saved = await updateCustomerCredit(saved.id, form); setCustomers((current) => [saved, ...current.filter((item) => item.id !== saved.id)]); setToast(modal?.id ? 'Cliente actualizado' : 'Cliente creado'); setModal(null); } catch (err) { setError(err.message); } };
  const mutate = async (action, customer) => { try { const updated = await action(customer.id); setCustomers((current) => current.map((item) => item.id === updated.id ? updated : item)); setToast('Cliente actualizado'); } catch (err) { setError(err.message); } };
  return <section className={`${styles.section} ${styles.softSection}`}>
    <div className={styles.adminPageHeader}><div><p className={styles.eyebrow}>Administración</p><h1>Clientes autorizados</h1><p>Gestiona cuentas, autorización comercial y datos regulatorios de la distribuidora.</p></div><div className={styles.adminHeaderActions}><button className={styles.secondaryButton} type="button" onClick={load}>Actualizar</button><button className={styles.primaryButton} type="button" onClick={() => { setForm(emptyCustomer); setModal({}); }}>Nuevo cliente</button></div></div>
    <div className={styles.metricGrid}>{[['active', 'Clientes activos'], ['pending', 'Pendientes/no autorizados'], ['noLicense', 'Sin licencia sanitaria'], ['credit', 'Crédito habilitado']].map(([key, label]) => <button key={key} type="button" className={metric === key ? styles.metricCardActive : ''} onClick={() => toggle(key)}><span>{label}</span><strong>{metrics[key]}</strong><small>Filtrar clientes</small></button>)}</div>
    <div className={styles.adminToolbar}><label className={styles.adminSearch}><span className={styles.srOnly}>Buscar clientes</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Razón social, RFC, correo o ciudad" /></label>{(query || metric) && <button className={styles.textButton} type="button" onClick={() => { setQuery(''); setMetric(''); }}>Limpiar filtros</button>}</div>
    {error && <p className={styles.formError}>{error}</p>}
    <div className={styles.tableWrapper}><table className={styles.adminDataTable}><thead><tr><th>Cliente</th><th>RFC</th><th>Contacto</th><th>Correo</th><th>Ciudad / Estado</th><th>Licencia</th><th>Autorización</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map((customer) => <tr key={customer.id}><td><strong>{customer.businessName}</strong><br /><small>{customer.commercialName || '—'}</small></td><td>{customer.rfc || '—'}</td><td>{customer.contactName}<br /><small>{customer.phone}</small></td><td>{customer.email}</td><td>{customer.city} / {customer.state}</td><td>{customer.sanitaryLicense || <StatusBadge tone="warning">Pendiente</StatusBadge>}</td><td><StatusBadge tone={customer.isAuthorized ? 'success' : 'warning'}>{customer.isAuthorized ? 'Autorizado' : 'Pendiente'}</StatusBadge></td><td><StatusBadge tone={customer.isActive ? 'success' : 'neutral'}>{customer.isActive ? 'Activo' : 'Inactivo'}</StatusBadge></td><td className={styles.actionsCell}><div className={styles.actionButtonsGroup}><button className={styles.actionButtonView} type="button" onClick={() => { setForm(formValues(customer)); setModal(customer); }}>Ver / editar</button><button className={styles.actionButtonEdit} type="button" onClick={() => mutate((id) => updateCustomerAuthorization(id, !customer.isAuthorized), customer)}>{customer.isAuthorized ? 'Bloquear' : 'Autorizar'}</button><button className={customer.isActive ? styles.actionButtonDeactivate : styles.actionButtonActivate} type="button" onClick={() => mutate((id) => updateCustomerStatus(id, !customer.isActive), customer)}>{customer.isActive ? 'Desactivar' : 'Activar'}</button></div></td></tr>)}</tbody></table></div>
    <CenterModal open={Boolean(modal)} title={modal?.id ? 'Editar cliente' : 'Nuevo cliente'} onClose={() => setModal(null)}><form className={styles.singleForm} onSubmit={save}><div className={styles.wizardGrid}>{[['name','Nombre de usuario'],['email','Correo'],['password', modal?.id ? 'Nueva contraseña (opcional)' : 'Contraseña inicial'],['businessName','Razón social'],['commercialName','Nombre comercial'],['rfc','RFC'],['contactName','Contacto'],['phone','Teléfono'],['address','Dirección'],['city','Ciudad'],['state','Estado'],['postalCode','Código postal'],['sanitaryLicense','Licencia sanitaria']].map(([field,label]) => <label key={field} className={field === 'address' ? styles.wizardFull : ''}>{label}<input required={!['commercialName','rfc','sanitaryLicense','password'].includes(field)} type={field === 'password' ? 'password' : 'text'} value={form[field]} onChange={(event) => setForm((current) => ({ ...current, [field]: event.target.value }))} /></label>)}<fieldset className={styles.wizardFull}><legend>Estado comercial</legend><label><input type="checkbox" checked={form.isAuthorized} onChange={(event) => setForm((current) => ({ ...current, isAuthorized: event.target.checked }))} /> Autorizar pedidos</label><label><input type="checkbox" checked={form.isActive} onChange={(event) => setForm((current) => ({ ...current, isActive: event.target.checked }))} /> Usuario activo</label></fieldset>{modal?.id && <fieldset className={styles.wizardFull}><legend>Crédito comercial (no habilita pagos)</legend><label><input type="checkbox" checked={form.creditEnabled} onChange={(event) => setForm((current) => ({ ...current, creditEnabled: event.target.checked }))} /> Crédito habilitado</label><label>Límite MXN<input min="0" step="0.01" type="number" value={form.creditLimit} onChange={(event) => setForm((current) => ({ ...current, creditLimit: event.target.value }))} /></label><label>Usado MXN<input min="0" step="0.01" type="number" value={form.creditUsed} onChange={(event) => setForm((current) => ({ ...current, creditUsed: event.target.value }))} /></label></fieldset>}</div><div className={styles.singleFormActions}><button className={styles.secondarySmall} type="button" onClick={() => setModal(null)}>Cancelar</button><button className={styles.primaryButton} type="submit">Guardar cliente</button></div></form></CenterModal><ToastMessage message={toast} onClose={() => setToast('')} />
  </section>;
}
