import { useState } from 'react';
import { confirmProductImport, previewProductImport, productImportTemplateUrl } from '../services/productImportService.js';
import styles from '../styles/App.module.css';

export default function AdminProductImportPage() {
  const [file, setFile] = useState(null); const [options, setOptions] = useState({ mode: 'create_or_update', createLaboratories: false, createCategories: false }); const [preview, setPreview] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const showPreview = async (event) => { event.preventDefault(); if (!file) { setError('Selecciona un archivo CSV.'); return; } try { setBusy(true); setPreview(await previewProductImport(file, options)); setResult(null); setError(''); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const confirm = async () => { try { setBusy(true); setResult(await confirmProductImport(preview.importId)); setError(''); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <section className={`${styles.section} ${styles.softSection}`}><div className={styles.adminPageHeader}><div><p className={styles.eyebrow}>Administración</p><h1>Importar productos</h1><p>Valida un archivo CSV antes de crear o actualizar el catálogo. No se descargan imágenes externas.</p></div><a className={styles.secondaryButton} href={productImportTemplateUrl}>Descargar plantilla CSV</a></div>
    <form className={styles.singleForm} onSubmit={showPreview}><section className={styles.formSection}><h3>1. Configura la importación</h3><div className={styles.wizardGrid}><label className={styles.wizardFull}>Archivo CSV<input type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files?.[0] || null)} required /></label><label>Modo<select value={options.mode} onChange={(event) => setOptions((current) => ({ ...current, mode: event.target.value }))}><option value="create_only">Crear solo nuevos</option><option value="update_existing">Actualizar existentes</option><option value="create_or_update">Crear y actualizar</option></select></label><fieldset><legend>Catálogos relacionados</legend><label><input type="checkbox" checked={options.createLaboratories} onChange={(event) => setOptions((current) => ({ ...current, createLaboratories: event.target.checked }))} /> Crear laboratorios faltantes</label><label><input type="checkbox" checked={options.createCategories} onChange={(event) => setOptions((current) => ({ ...current, createCategories: event.target.checked }))} /> Crear categorías faltantes</label></fieldset></div></section>{error && <p className={styles.formError}>{error}</p>}<div className={styles.singleFormActions}><a className={styles.secondarySmall} href="#/admin/productos">Volver a productos</a><button className={styles.primaryButton} disabled={busy} type="submit">{busy ? 'Validando...' : 'Ver vista previa'}</button></div></form>
    {preview && <section className={styles.reportPreview}><div className={styles.reportToolbar}><div><strong>{preview.totalRows} filas analizadas</strong><p>{preview.validRows} válidas · {preview.invalidRows} con errores · {preview.creates} nuevas · {preview.updates} actualizaciones</p></div><button className={styles.primarySmall} type="button" disabled={busy || preview.validRows === 0 || Boolean(result)} onClick={confirm}>{busy ? 'Importando...' : 'Confirmar importación'}</button></div>{(preview.missingLaboratories.length > 0 || preview.missingCategories.length > 0) && <p className={styles.activeFilterNotice}>Se crearán: {preview.missingLaboratories.join(', ') || 'sin laboratorios'} {preview.missingCategories.length ? ` · categorías: ${preview.missingCategories.join(', ')}` : ''}</p>}<div className={styles.tableWrapper}><table className={styles.adminDataTable}><thead><tr><th>Fila</th><th>SKU</th><th>Acción</th><th>Validación</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.line}><td>{row.line}</td><td>{row.sku}</td><td>{row.action === 'create' ? 'Crear' : 'Actualizar'}</td><td>{row.errors.length ? row.errors.join('; ') : 'Correcta'}</td></tr>)}</tbody></table></div></section>}
    {result && <section className={styles.emptyState}><h2>Importación completada</h2><p>{result.created} creados, {result.updated} actualizados y {result.skipped} omitidos.</p><a className={styles.primaryButton} href="#/admin/productos">Ver productos</a></section>}
  </section>;
}
